name: Sincronizador Omie-Tray
on:
  schedule:
    - cron: '*/15 * * * *' # Roda a cada 15 minutos
  workflow_dispatch: # Permite que você rode manualmente se quiser

jobs:
  sincronizar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependencias
        run: pip install requests

      - name: Executar Sincronizacao
        env:
          OMIE_APP_KEY: ${{ secrets.OMIE_APP_KEY }}
          OMIE_APP_SECRET: ${{ secrets.OMIE_APP_SECRET }}
          TRAY_ENDPOINT: ${{ secrets.TRAY_ENDPOINT }}
        run: python main.py
